counties = [
    {"county_code": 1, "county_name": "Stockholms län"},
    {"county_code": 3, "county_name": "Uppsala län"},
    {"county_code": 4, "county_name": "Södermanlands län"},
    {"county_code": 5, "county_name": "Östergötlands län"},
    {"county_code": 6, "county_name": "Jönköpings län"},
    {"county_code": 7, "county_name": "Kronobergs län"},
    {"county_code": 8, "county_name": "Kalmar län"},
    {"county_code": 9, "county_name": "Gotlands län"},
    {"county_code": 10, "county_name": "Blekinge län"},
    {"county_code": 12, "county_name": "Skåne län"},
    {"county_code": 13, "county_name": "Hallands län"},
    {"county_code": 14, "county_name": "Västra Götalands län"},
    {"county_code": 18, "county_name": "Örebro län"},
    {"county_code": 19, "county_name": "Västmanlands län"},
    {"county_code": 20, "county_name": "Dalarnas län"},
    {"county_code": 21, "county_name": "Gävleborgs län"},
    {"county_code": 22, "county_name": "Västernorrlands län"},
    {"county_code": 23, "county_name": "Jämtlands län"},
    {"county_code": 24, "county_name": "Västerbottens län"},
    {"county_code": 25, "county_name": "Norrbottens län"},
]