keepers = [
        {
            name: "Gyllene Droppen Honung AB",
            tags: ["Yrkesbiodlare", "Gårdsbutik", "Ljunghonung", "Kakhonung"],
            location: "Göteborg",
            picture: "https://placecats.com/neo/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
        {
            name: "Binas Rike Biodling",
            tags: ["Maskroshonung", "Bladhonung", "Trädsgårdshonung", "Andelsbiodling", "Studiebesök"],
            location: "Båstad",
            picture: "https://placecats.com/poppy/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
        {
            name: "Surr & Sött",
            tags: ["Hobbybiodlare", "Gårdsbutik", "Ljunghonung", "Kurser och föreläsningar", "Trädsgårdshonung"],
            location: "Uppsala",
            picture: "https://placecats.com/neo_banana/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
        {
            name: "Blomsterängens Bikupor",
            tags: ["Yrkesbiodlare", "Gårdsbutik", "Marknadsförsäljning", "Andelsbiodling", "Trädsgårdshonung"],
            location: "Växjö",
            picture: "https://placecats.com/louie/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Honungsverket",
            tags: ["Maskroshonung", "Gårdsbutik", "Kurser och föreläsningar", "Bladhonung", "Trädsgårdshonung"],
            location: "Malmö",
            picture: "https://placecats.com/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Jonnas biodling",
            tags: ["Rökt honung","Bladhonung","Andelsbiodling","Studiebesök","Yrkesbiodlare"],
            location: "Linköping",
            picture: "https://placecats.com/neo/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Boris Bin",
            tags: ["Trädsgårdshonung","Gårdsbutik","Hobbybiodlare",],
            location: "Stockholm",
            picture: "https://placecats.com/millie/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Kupkulturen",
            tags: ["Andelsbiodling", "Kurser och föreläsningar", "Studiebesök", "Hobbybiodlare",],
            location: "Jönköping",
            picture: "https://placecats.com/millie_neo/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Hexagons are the bestagons",
            tags: ["Kakhonung", "Marknadsförsäljning",],
            location: "Kalmar",
            picture: "https://placecats.com/neo_banana/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Bee Kind",
            tags: ["Maskroshonung", "Rökt honung", "Studiebesök", "Hobbybiodlare",],
            location: "Lund",
            picture: "https://placecats.com/poppy/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Hedvig Elisabeth Charlottas biodling",
            tags: ["Yrkesbiodlare", "Gårdsbutik", "Bladhonung", "Maskroshonung", "Ljunghonung"],
            location: "Kungälv",
            picture: "https://placecats.com/bella/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Drottning Blankas döttrar",
            tags: ["Hobbybiodlare", "Trädsgårdshonung", "Gårdsbutik"],
            location: "Varberg",
            picture: "https://placecats.com/g/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Sticky stuff",
            tags: ["Hobbybiodlare", "Studiebesök", "Trädsgårdshonung", "Ljunghonung"],
            location: "Mölndal",
            picture: "https://placecats.com/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Beelzebubs buzz",
            tags: ["Rökt honung", "Andelsbiodling", "Kurser och föreläsningar", "Yrkesbiodlare"],
            location: "Partille",
            picture: "https://placecats.com/louie/300/200",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
            {
            name: "Gyllene näktar",
            tags: ["Trädsgårdshonung", "Marknadsförsäljning", "Gårdsbutik", "Yrkesbiodlare"],
            location: "Uddevalla",
            picture: "https://placecats.com/millie/300/250",
            link: "https://sv.wikipedia.org/wiki/Biodling",
        },
    ]